### ISSUE TITLE
How does this compare with wai-bindgen?

### ISSUE THREAD

**Issue by archseer** [jedisct1/witx-codegen#14]
I've been looking at [wai-bindgen](https://github.com/bytecodealliance/wai-bindgen) (formerly witx-bindgen), but I found that witx-codegen seems to support more targets (AssemblyScript, Zig)

**Comment by jedisct1** [comment]
`witx-codegen` keeps data represented the same way no matter what language is used. The generated code is simple and readable, the tool is mature and the output format is stable and matches the current ABI used by all WASI modules.

`wai-bindgen` transforms the data representation before and after every function call, possibly requiring dynamic memory allocations. The generated code is only meant to be read by the compiler, and the tool is still a work in progress. I was not able to use it on real-world definitions without it crashing or reporting unsupported constructs.

However, `wai-bindgen` was made to support a new, completely different calling convention for WebAssembly designed to eventually replace the current one for WASI modules. 

WebAssembly is still shaping up, but things will be really great once everything is stabilized.
