### ISSUE TITLE
Library API

### ISSUE THREAD

**Issue by XAMPPRocky** [jedisct1/witx-codegen#7]
Hello, I’m really interested in this project, and have already been trying it out in a few of my own. One thing I was wondering is if you would be interested in exposing a library API for the WITX syntax tree? Obviously `witx-codegen` Is understandably focused on generating WASI bindings, but I’m interested in extending to generate bindings for other formats, such as C headers with cbindgen. I’m happy to deal with the library API being very unstable and changing each version.

**Comment by jedisct1** [comment]
Hi!

Sure, any new and useful backend that would be welcome!

Can you clarify what you mean by library API? C headers and Typescript definitions?

**Comment by XAMPPRocky** [comment]
Well by library API I mean that there is a crate with a library function like `fn parse(witx: &str) -> Result<WitxAst>` where `WitxAst` is some type representing a witx document.

I think ideally (though would take longer to build), would be something like `syn` but for witx, where you can easily parse and modify the syntax.

I essentially want to use WITX as an Interface Description Language for generating API bindings for my Rust library for C applications to be able as well as WASM from a single definition.

**Comment by jedisct1** [comment]
Isn't it what the [witnext](https://docs.rs/witnext/0.10.0-beta1/witnext/) crate does?

The way types are represented is a little bit messy compared to the `ASType` type we have in `witx-codegen`, but if you are looking for something very low level, this may fit the bill.

**Comment by XAMPPRocky** [comment]
I hadn't heard of that crate, thanks for sharing! That is what I'm looking for.

**Comment by XAMPPRocky** [comment]
Hey, do you happen to know where the source code for witnext is? The repository points to the wasi repo but I can’t find it there.
