### ISSUE TITLE
Compatibility with WASI's (ephimeral) specs

### ISSUE THREAD

**Issue by ryankurte** [jedisct1/witx-codegen#8]
hey thanks for making a neat thing! have been playing with this alongside bytecodealiance's [wiggle](https://crates.io/crates/wiggle) to try and generate both runtime and library bindings, and it seems that for a couple of reasons one can't write `witx` files usable by both. using the files from the the [WITX WASI spec](https://github.com/WebAssembly/WASI/tree/main/phases) for testing this _appears_ to be because:

- witx-codegen expects `(use * from MODULE)` where wiggle prefers `(use "MODULE.witx")`
- witx-codegen requires a top-level module, wiggle expects functions to be in modules and types to be global (mapped to a meta `types` module on generation)

there's a note in the readme about the latter requirement, just wondering if you'd be open to the changes required to make these play nicely?

**Comment by jedisct1** [comment]
Hi Ryan!

Unfortunately, the WITX spec is constantly changing. Every release of the witx crate also comes with major breaking changes, which makes it painful for code generators to keep up.

If you manage to add compatibility with `witx 0.9`, that would be fantastic!

The types already have an abstraction (`ASType`) that the `witx 0.9` types can easily map to. But modules, function, etc. are directly using the `witnext` API that is slightly different from `witx 0.9`. Maybe an abstraction here would be useful, too.

Anyway, your help would be definitely more than welcome!

**Comment by ryankurte** [comment]
> Unfortunately, the WITX spec is constantly changing. Every release of the witx crate also comes with major breaking changes, which makes it painful for code generators to keep up.

oh wow that is frustrating, i've been trying to find a spec and it appears the implementation is, all there is? also where does `witnext` actually come from? the manifest suggests [here](https://github.com/WebAssembly/WASI) but, there's only `witx` as far as i can see.

**Comment by jedisct1** [comment]
I don't think there's a spec; the implementation is.

The WebAssembly ABI itself is going to change and [the abi-next branch](https://github.com/alexcrichton/WASI/tree/abi-next/tools/witx) is how the s-expressions based witx format needs to be changed to support it. This is what `witnext` is. But Alex is also experimenting with a completely different syntax (witx2).

Let's be positive. Eventually, these efforts will converge towards one good, stable syntax that won't have to depend on a specific implementation.

**Comment by aergonaut** [comment]
Reading @ryankurte's OP, is it possible to have 2 WITX files, one formatted like witx-codegen prefers and one formatted like wiggle prefers, as long as both files describe the same types/functions/etc.? I don't know WITX too well, so I'm not sure if the differences pointed out in the OP would mean the WITX is describing fundamentally different modules.

**Comment by jedisct1** [comment]
It's totally possible to have 2 WITX files. Besides minor syntax differences, they would describe exactly the same API.
